/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./../components/search/jp/Article.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    ChangesPreview: typeof import('./../components/edits/ChangesPreview.vue')['default']
    Description: typeof import('./../components/search/jp/the-article/Description.vue')['default']
    ExternalInTextLink: typeof import('./../components/ExternalInTextLink.vue')['default']
    FullArticle: typeof import('./../components/edits/full-article.vue')['default']
    Meaning: typeof import('./../components/search/jp/the-article/Meaning.vue')['default']
    Panel: typeof import('./../components/search/Panel.vue')['default']
    PanelBody: typeof import('./../components/search/PanelBody.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./../components/search/SearchButton.vue')['default']
    ShortArticle: typeof import('./../components/edits/short-article.vue')['default']
    Tags: typeof import('./../components/Tags.vue')['default']
    TextBetween: typeof import('./../components/text-between.vue')['default']
    TextSplitted: typeof import('./../components/text-splitted.vue')['default']
    TheAppHeader: typeof import('./../components/TheAppHeader.vue')['default']
    TheArticle: typeof import('./../components/search/kanji/the-article.vue')['default']
    TheForms: typeof import('./../components/search/kanji/the-article/the-forms.vue')['default']
    TheHandwriting: typeof import('./../components/search/TheHandwriting.vue')['default']
    TheHeader: typeof import('./../components/the-header.vue')['default']
    TheImages: typeof import('./../components/search/kanji/the-article/the-images.vue')['default']
    TheIndices: typeof import('./../components/search/kanji/the-article/the-indices.vue')['default']
    TheInput: typeof import('./../components/search/TheInput.vue')['default']
    TheJpnGrammar: typeof import('./../components/search/jp/TheJpnGrammar.vue')['default']
    TheKanjis: typeof import('./../components/search/jp/the-article/the-kanjis.vue')['default']
    TheMeanings: typeof import('./../components/search/kanji/the-article/the-meanings.vue')['default']
    ThemeSwitcher: typeof import('./../components/theme-switcher.vue')['default']
    TheModeSelector: typeof import('./../components/search/TheModeSelector.vue')['default']
    TheReading: typeof import('./../components/search/kanji/the-article/the-reading.vue')['default']
    TheSuggs: typeof import('./../components/search/TheSuggs.vue')['default']
    TheWeeaboo: typeof import('./../components/TheWeeaboo.vue')['default']
    TheWords: typeof import('./../components/search/kanji/the-article/the-words.vue')['default']
    TotalStats: typeof import('./../components/total-stats.vue')['default']
    UserBar: typeof import('./../components/search/jp/the-article/UserBar.vue')['default']
    UserProfile: typeof import('./../components/edits/user-profile.vue')['default']
    ViewMode: typeof import('./../components/search/jp/the-article/ViewMode.vue')['default']
    Words: typeof import('./../components/search/jp/the-article/Words.vue')['default']
  }
}
