name: Deploy

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: build
        run: |
          npm ci
          npm run build --if-present
          
      - uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /var/www/static/
          remote_host: ${{ secrets.SSH_SERVER }}
          remote_user: nyars
          remote_key: ${{ secrets.SSH_KEY }}