name: Deploy

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_SERVER: ${{secrets.SSH_SERVER}}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: deploy
      - run: |
          npm ci
          npm run build --if-present
          mkdir ~/.ssh
          'echo "$SSH_KEY" >> ~/.ssh/github-action'
          chmod 400 ~/.ssh/github-action
          echo -e "Host nyars\n\tUser nyars\n\tHostname $SSH_SERVER\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
          rsync -e ssh dist nyars:/var/www/static
