name: ESLint

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  schedule:
    - cron: "33 22 * * 0"

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm ci

      - name: Generate ESLint report
        run: pnpm lint-report
        if: github.event_name != 'pull_request'
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        if: github.event_name != 'pull_request'
        with:
          sarif_file: eslint-results.sarif

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
